# Project: 项目9
# Makefile created by Dev-C++ 6.7.5

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main.o
LINKOBJ  = main.o
LIBS     = -L"C:/Users/LQY-PC/AppData/Roaming/gcc/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/10.3.0/" -L"C:/Users/LQY-PC/AppData/Roaming/gcc/Dev-Cpp/MinGW64/lib/gcc/" -L"C:/Users/LQY-PC/AppData/Roaming/gcc/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib/" -L"C:/Users/LQY-PC/AppData/Roaming/gcc/Dev-Cpp/MinGW64/lib/" -L"C:/Users/LQY-PC/AppData/Roaming/gcc/Dev-Cpp/MinGW64/lib" -L"C:/Users/LQY-PC/AppData/Roaming/gcc/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -g3 -mwindows -lm -lfreeglut_static -lopengl32 -lwinmm -lgdi32 -static
INCS     = -I"C:/Users/LQY-PC/AppData/Roaming/gcc/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/10.3.0/include" -I"C:/Users/LQY-PC/AppData/Roaming/gcc/Dev-Cpp/MinGW64/include" -I"C:/Users/LQY-PC/AppData/Roaming/gcc/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/10.3.0/include-fixed" -I"C:/Users/LQY-PC/AppData/Roaming/gcc/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include"
CXXINCS  = -I"C:/Users/LQY-PC/AppData/Roaming/gcc/Dev-Cpp/MinGW64/include/c++/10.3.0" -I"C:/Users/LQY-PC/AppData/Roaming/gcc/Dev-Cpp/MinGW64/include/c++/10.3.0/x86_64-w64-mingw32" -I"C:/Users/LQY-PC/AppData/Roaming/gcc/Dev-Cpp/MinGW64/include/c++/10.3.0/backward" -I"C:/Users/LQY-PC/AppData/Roaming/gcc/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/10.3.0/include" -I"C:/Users/LQY-PC/AppData/Roaming/gcc/Dev-Cpp/MinGW64/include" -I"C:/Users/LQY-PC/AppData/Roaming/gcc/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/10.3.0/include-fixed" -I"C:/Users/LQY-PC/AppData/Roaming/gcc/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include"
BIN      = 项目9.exe
CXXFLAGS = $(CXXINCS) -Wall -Wextra -g3
ENCODINGS = -finput-charset=utf-8 -fexec-charset=gbk
CFLAGS   = $(INCS) -Wall -Wextra -g3
RM       = del /q /f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "$(BIN)" $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS) 
